# Generated by Django 4.1.5 on 2023-02-20 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='Department_ID',
        ),
    ]
